Repository tradingview/lightweight-charts, pull requests merged in 2023-09, with the labels that each got.

#1424 DOCS: landing page css fixes
  website/src/components/landing-page/CTAButton/ctabutton.module.css
  website/src/pages/index.module.css
Labels: website

#1412 Add option to set minimum dimension for scales
  .size-limit.js
  src/api/options/price-scale-options-defaults.ts
  src/api/options/time-scale-options-defaults.ts
  src/gui/chart-widget.ts
  src/model/price-scale.ts
  src/model/time-scale.ts
  tests/e2e/graphics/test-cases/price-scale/minimum-scale-dimensions.js
Labels: polish

#1411 add `paneSize` getter to IChartApi
  .size-limit.js
  src/api/chart-api.ts
  src/api/ichart-api.ts
  src/gui/chart-widget.ts
Labels: polish

#1360 Spring cleaning
  src/helpers/algorithms.ts
  src/helpers/canvas-helpers.ts
  src/helpers/mathex.ts
  src/model/data-layer.ts
  src/model/plot-list.ts
  src/model/price-scale-conversions.ts
  src/model/price-tick-span-calculator.ts
  src/model/tick-marks.ts
  src/model/time-data.ts
  src/model/time-scale.ts
  tests/e2e/graphics/test-cases/constrast-colors.js
Labels: enhancement, polish

#1330 fix: Add an option to disable crosshair (#749)
  .size-limit.js
  src/model/crosshair.ts
  src/views/pane/crosshair-marks-pane-view.ts
  src/views/pane/crosshair-pane-view.ts
  src/views/price-axis/crosshair-price-axis-view.ts
  src/views/time-axis/crosshair-time-axis-view.ts
  tests/e2e/graphics/test-cases/applying-options/crosshair-mode-hidden-unhide.js
  tests/e2e/graphics/test-cases/applying-options/crosshair-mode-hidden.js
  tests/e2e/graphics/test-cases/initial-options/crosshair-mode-hidden.js
Labels: enhancement
