Repository tradingview/lightweight-charts, pull requests merged in 2024-03, with the labels that each got.

#1538 fix: marker positioning
  .size-limit.js
  src/model/price-scale.ts
  src/views/pane/series-markers-pane-view.ts
  tests/e2e/graphics/test-cases/series-markers/series-markers-all-above.js
  tests/e2e/graphics/test-cases/series-markers/series-markers-all-below.js
  tests/e2e/graphics/test-cases/series-markers/series-markers-all-inbar.js
Labels: bug

#1543 Fix puppeteer installation on CI
  .puppeteerrc.js
Labels: infrastructure

#1550 fix showLabels option on trend-line plugin example
  plugin-examples/src/plugins/trend-line/trend-line.ts
Labels: bug, polish, plugin
