Repository tradingview/lightweight-charts, pull requests merged in 2025-01, with the labels that each got.

#1758 CLL-314: add prototype pollution protection for merge helper function
  .size-limit.js
  src/helpers/strict-type-checks.ts
  tests/unittests/helpers.spec.ts
Labels: enhancement

#1776 don't draw crosshair lines after mouse leaves chart pane
  src/model/crosshair.ts
  tests/e2e/graphics/helpers/screenshoter.ts
  tests/e2e/graphics/test-cases/.eslintrc.cjs
  tests/e2e/graphics/test-cases/dont-draw-crosshair-lines-when-mouse-leave.js
  tests/e2e/helpers/perform-interactions.ts
  tests/e2e/interactions/interactions-test-cases.ts
Labels: bug

#1773 WRT-1291: Describe how to remove gaps
  website/docs/time-scale.md
  website/static/img/extra-margin.png
  website/static/img/margin.png
Labels: documentation
