Repository tradingview/lightweight-charts, pull requests merged in 2025-03, with the labels that each got.

#1835 Performance Optimization for Charts with Markers and Large Datasets
  src/plugins/series-markers/primitive.ts
  website/docs/release-notes.md
Labels: enhancement, plugin

#1840 Prevent crosshair marker visible on load
  debug/default/index.html
  debug/default/index.ts
  src/model/crosshair.ts
  tests/e2e/graphics/test-cases/crosshair-visible-startup.js
  website/docusaurus.config.js
Labels: bug

#1842 WRT-1390: Time scale proofreading
  website/docs/time-scale.md
Labels: documentation
