Repository tradingview/lightweight-charts, pull requests merged in 2025-05, with the labels that each got.

#1880 update dependencies in plugin-examples folder
  plugin-examples/package-lock.json
  plugin-examples/package.json
Labels: dependencies

#1876 add options to series markers to change rendering zOrder
  debug/default/index.ts
  src/plugins/series-markers/options.ts
  src/plugins/series-markers/pane-view.ts
  src/plugins/series-markers/primitive.ts
  src/plugins/series-markers/renderer.ts
  src/plugins/series-markers/wrapper.ts
  tests/e2e/graphics/test-cases/series-markers/series-markers-zorder.js
Labels: enhancement, plugin

#1856 feat: boundaries price marks
  src/api/iprice-scale-api.ts
  src/api/options/price-scale-options-defaults.ts
  src/api/price-scale-api.ts
  src/index.ts
  src/model/price-scale.ts
  src/model/price-tick-mark-builder.ts
  tests/e2e/coverage/test-cases/price-scale/change-auto-scale.js
  tests/e2e/coverage/test-cases/price-scale/change-edge-marks.js
  tests/e2e/graphics/test-cases/price-scale/edge-marks-disabled-on-auto-scale-off.js
  tests/e2e/graphics/test-cases/price-scale/edge-marks-enabled-on-auto-scale-on.js
  tests/e2e/graphics/test-cases/price-scale/edge-marks-logarithmic.js
  tests/e2e/graphics/test-cases/price-scale/edge-marks.js
  tests/e2e/graphics/test-cases/price-scale/set-visible-range.js
  tests/e2e/graphics/test-cases/price-scale/toggle-auto-scale.js
Labels: enhancement
