Repository tradingview/lightweight-charts, pull requests merged in 2025-02, with the labels that each got.

#1800 suppress ResizeObserver error overlay in dev mode
  website/docusaurus.config.js
  website/plugins/suppress-resize-observer-error/index.js
Labels: website

#1803 WRT-1307: Change wording in series-types.mdx
  website/docs/series-types.mdx
Labels: documentation

#1807 hide crosshair mark on mouseleave
  src/views/pane/crosshair-marks-pane-view.ts
Labels: bug
